version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - "novusvetus"
    reviewers:
      - "novusvetus"
    labels:
      - "maintenance"
      - "dependencies"
    open-pull-requests-limit: 10

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"
    assignees:
      - "novusvetus"
    reviewers:
      - "novusvetus"
    labels:
      - "maintenance"
      - "dependencies"
    open-pull-requests-limit: 10
